export const THEMES = [
    "light",
    "dark",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthwave",
    "retro",
    "cyberpunk",
    "valentine",
    "halloween",
    "garden",
    "forest",
    "aqua",
    "lofi",
    "pastel",
    "fantasy",
    "wireframe",
    "black",
    "luxury",
    "dracula",
    "cmyk",
    "autumn",
    "business",
    "acid",
    "lemonade",
    "night",
    "coffee",
    "winter",
    "dim",
    "nord",
    "sunset",
];

export const THEMES_WITH_COLORS = [
    {
        name: "light",
        colors: {
            base: "#ffffff",
            primary: "#570df8",
            secondary: "#f000b8",
            accent: "#37cdbe",
            neutral: "#3d4451",
        },
    },
    {
        name: "dark",
        colors: {
            base: "#1d232a",
            primary: "#661ae6",
            secondary: "#d926aa",
            accent: "#1fb2a6",
            neutral: "#2a2e37",
        },
    },
    {
        name: "cupcake",
        colors: {
            base: "#faf7f5",
            primary: "#6572eb",
            secondary: "#61afef",
            accent: "#a7d2e0",
            neutral: "#483699",
        },
    },
    {
        name: "bumblebee",
        colors: {
            base: "#fef9e3",
            primary: "#e0a82e",
            secondary: "#f9d72f",
            accent: "#1e3743",
            neutral: "#2a2e37",
        },
    },
    {
        name: "emerald",
        colors: {
            base: "#ffffff",
            primary: "#66cc8a",
            secondary: "#377d71",
            accent: "#ea6e94",
            neutral: "#33182b",
        },
    },
    {
        name: "corporate",
        colors: {
            base: "#ffffff",
            primary: "#4b6bfb",
            secondary: "#7b92b2",
            accent: "#67c9c0",
            neutral: "#3d4451",
        },
    },
    {
        name: "synthwave",
        colors: {
            base: "#2b2040",
            primary: "#e779c1",
            secondary: "#5ad0ed",
            accent: "#ea92e5",
            neutral: "#20143a",
        },
    },
    {
        name: "retro",
        colors: {
            base: "#efe6cb",
            primary: "#ef9995",
            secondary: "#a4cbb4",
            accent: "#ebdc99",
            neutral: "#282424",
        },
    },
    {
        name: "cyberpunk",
        colors: {
            base: "#1d1d1d",
            primary: "#ff7ac6",
            secondary: "#75d1f0",
            accent: "#fbd72a",
            neutral: "#423f4a",
        },
    },
    {
        name: "valentine",
        colors: {
            base: "#ffeefa",
            primary: "#e96e94",
            secondary: "#9d44e5",
            accent: "#ed6468",
            neutral: "#6d3a3a",
        },
    },
    {
        name: "halloween",
        colors: {
            base: "#212121",
            primary: "#ff8200",
            secondary: "#6d5423",
            accent: "#be5e1d",
            neutral: "#5c4118",
        },
    },
    {
        name: "garden",
        colors: {
            base: "#f7faf3",
            primary: "#5c7f67",
            secondary: "#ead29b",
            accent: "#a991f7",
            neutral: "#2f2f2f",
        },
    },
    {
        name: "forest",
        colors: {
            base: "#141e12",
            primary: "#1eb854",
            secondary: "#1ad6ad",
            accent: "#e0d720",
            neutral: "#1c2e17",
        },
    },
    {
        name: "aqua",
        colors: {
            base: "#091c29",
            primary: "#09e6c1",
            secondary: "#966f91",
            accent: "#377d71",
            neutral: "#071b2a",
        },
    },
    {
        name: "lofi",
        colors: {
            base: "#ffffff",
            primary: "#4d4d4d",
            secondary: "#808080",
            accent: "#000000",
            neutral: "#1c1c1c",
        },
    },
    {
        name: "pastel",
        colors: {
            base: "#f9fafb",
            primary: "#d1c1d7",
            secondary: "#f6adc6",
            accent: "#f4f8e6",
            neutral: "#7d729b",
        },
    },
    {
        name: "fantasy",
        colors: {
            base: "#191e24",
            primary: "#6e6e73",
            secondary: "#19808a",
            accent: "#ea6e94",
            neutral: "#2a2e37",
        },
    },
    {
        name: "wireframe",
        colors: {
            base: "#ffffff",
            primary: "#b8b8b8",
            secondary: "#b8b8b8",
            accent: "#b8b8b8",
            neutral: "#b8b8b8",
        },
    },
    {
        name: "black",
        colors: {
            base: "#000000",
            primary: "#373737",
            secondary: "#4a4a4a",
            accent: "#5a5a5a",
            neutral: "#1d1d1d",
        },
    },
    {
        name: "luxury",
        colors: {
            base: "#0d0a0a",
            primary: "#a78bfa",
            secondary: "#e879f9",
            accent: "#d97706",
            neutral: "#404040",
        },
    },
    {
        name: "dracula",
        colors: {
            base: "#282a36",
            primary: "#ff79c6",
            secondary: "#bd93f9",
            accent: "#ffb86c",
            neutral: "#44475a",
        },
    },
    {
        name: "cmyk",
        colors: {
            base: "#ffffff",
            primary: "#45aae6",
            secondary: "#d926aa",
            accent: "#8066ff",
            neutral: "#3a414e",
        },
    },
    {
        name: "autumn",
        colors: {
            base: "#f1f1e6",
            primary: "#854513",
            secondary: "#7e2f5b",
            accent: "#a93321",
            neutral: "#321d00",
        },
    },
    {
        name: "business",
        colors: {
            base: "#1a2e3a",
            primary: "#1c1c1c",
            secondary: "#6e6e6e",
            accent: "#4e4e4e",
            neutral: "#2a2e37",
        },
    },
    {
        name: "acid",
        colors: {
            base: "#ffffff",
            primary: "#393939",
            secondary: "#696969",
            accent: "#a8a8a8",
            neutral: "#8c8c8c",
        },
    },
    {
        name: "lemonade",
        colors: {
            base: "#ffffff",
            primary: "#544605",
            secondary: "#9e5f03",
            accent: "#b94a20",
            neutral: "#3d4451",
        },
    },
    {
        name: "night",
        colors: {
            base: "#0f0e0e",
            primary: "#3967a5",
            secondary: "#f4f4f4",
            accent: "#212121",
            neutral: "#171616",
        },
    },
    {
        name: "coffee",
        colors: {
            base: "#20160F",
            primary: "#d99042",
            secondary: "#26353d",
            accent: "#804c2c",
            neutral: "#271c19",
        },
    },
    {
        name: "winter",
        colors: {
            base: "#ffffff",
            primary: "#047AFF",
            secondary: "#463AA2",
            accent: "#C148AC",
            neutral: "#021431",
        },
    },
    {
        name: "dim",
        colors: {
            base: "#1a232e",
            primary: "#7f7f7f",
            secondary: "#bfbfbf",
            accent: "#d9d9d9",
            neutral: "#2a2e37",
        },
    },
    {
        name: "nord",
        colors: {
            base: "#2e3440",
            primary: "#81a1c1",
            secondary: "#a3be8c",
            accent: "#bf616a",
            neutral: "#3b4252",
        },
    },
    {
        name: "sunset",
        colors: {
            base: "#fbf7f4",
            primary: "#e16723",
            secondary: "#e07a5f",
            accent: "#f7b886",
            neutral: "#3d4451",
        },
    },
  ];